---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: puphpet/debian75-x64
        memory: '2048'
        hostname: drupal-dev.local
        chosen_provider: virtualbox
        network:
            private_network: 172.16.10.10
            forwarded_port:
                WDjb3QgpfP4u:
                    host: '8754'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            umcFb7AF9Z9o:
                source: /www/drupal-dev/drupal7
                target: /var/www/drupal7
                sync_type: nfs
                rsync:
                    auto: 'false'
            bzlyuQf3NbvC:
                source: /www/drupal-dev/drupal8
                target: /var/www/drupal8
                sync_type: nfs
                rsync:
                    auto: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - ruby
        - php-apc
        - php5-memcache
        - memcached
        - php5-curl
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        n06BO0eaNzH7:
            servername: drupal7.local
            docroot: /var/www/drupal7
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        HPLuMjwkX2Yr:
            servername: drupal8.local
            docroot: /var/www/drupal8
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: 0
    vhosts:
        Nx4NvQcFlDyg:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
            - memcached
        pear:
            - PHP_CodeSniffer
            - console_table
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Australia/Melbourne
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '0'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '1000'
drush:
    install: '1'
    settings:
        drush.tag_branch: master
mysql:
    install: '1'
    root_password: root
    adminer: 0
    databases:
        2sIaIkYF1rzJ:
            grant:
                - ALL
            name: drupal7
            host: localhost
            user: admin
            password: password
            sql_file: ''
        x7ABSiIOjto6:
            grant:
                - ALL
            name: drupal8
            host: localhost
            user: admin
            password: password
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

